variables:
  DOCKER_TLS_CERTDIR: "/certs"
  # DOCKER_HOST: "tcp://docker:2375"


default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  tags:
    - docker
    - dind
    - buildx
    - builder

build-buildx-with-cache:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CACHE_IMAGE: $CI_REGISTRY_IMAGE:cache
  stage: build
  tags:
    - docker
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker context create cached-builder
    - docker buildx create --use --driver docker-container cached-builder
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build
      --cache-from type=registry,ref=$CACHE_IMAGE
      --cache-to type=registry,ref=$CACHE_IMAGE,mode=max
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --push .
  after_script:
    - docker buildx rm cached-builder

.build-buildx-with-cache-custom:
  image: ghcr.io/rolling-space/devcontainer/images/devcontainer-cli:latest
  services:
    - docker:dind
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --driver docker-container --name cached-custom-builder
    - docker buildx inspect --bootstrap
  variables:
    CACHE_IMAGE: $CI_REGISTRY_IMAGE:custom-cache
  script:
    - docker buildx build
      --cache-from type=registry,ref=$CACHE_IMAGE
      --cache-to type=registry,ref=$CACHE_IMAGE,mode=max
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-custom
      --push .
  after_script:
    - docker buildx rm cached-custom-builder

build-buildah:
  stage: build
  image: quay.io/buildah/stable
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but Buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
    # Write all image metadata in the docker format, not the standard OCI format.
    # Newer versions of docker can handle the OCI format, but older versions, like
    # the one shipped with Fedora 30, cannot handle the format.
    BUILDAH_FORMAT: docker
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE/test"
  before_script:
    # GitLab container registry credentials taken from the
    # [predefined CI/CD variables](../variables/_index.md#predefined-cicd-variables)
    # to authenticate to the registry.
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah images
    - buildah build -t $FQ_IMAGE_NAME
    - buildah images
    - buildah push $FQ_IMAGE_NAME

