name: Test ruby feature

on:
  push:

jobs:
  build:
    name: Test ruby feature

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/rolling-space/devcontainer/test-ruby-feature
          cacheFrom: ghcr.io/rolling-space/devcontainer/test-ruby-feature
          subFolder: .github
          refFilterForPush: refs/heads/main
          runCmd: RUBY_YJIT_ENABLE=1 ruby -v | grep +YJIT || ( echo "Ruby is not installed."; exit 1 )
